/* Standalone original PLAY rhythm page. It receives its data from index(2).html. */
const $=id=>document.getElementById(id);
const params=new URLSearchParams(location.search);
const selectedNowPlaySong=Number(params.get('song')||0);
const selectedNowPlayDifficulty=params.get('difficulty')||'EASY';
const GAMEPLAY_SONGS={0:'assets/song-01_[cut_98sec].mp3',1:'assets/song-022_[cut_133sec].mp3'};
const NOW_PLAY_SONGS={0:{name:'VIRTUAL TO LIVE'},1:{name:'BOUNCE'}};
let gameplayAudio=null,gameplayFrame=null,gameplayNotes=[],score=0,combo=0,perfect=0,great=0,okay=0,miss=0,ended=false;
const HIT=.22;
function createNotes(){const chart=[[2,0,'tap',0],[2.55,1,'tap',0],[3.1,2,'tap',0],[3.65,3,'tap',0],[4.2,0,'tap',0],[4.65,2,'tap',0],[5.1,1,'tap',0],[5.55,3,'tap',0],[6.1,0,'hold',.9],[7.2,2,'tap',0],[7.65,3,'tap',0],[8.1,1,'hold',.8],[9.15,0,'tap',0],[9.6,1,'tap',0],[10.05,2,'tap',0],[10.5,3,'tap',0],[11.1,3,'hold',1],[12.25,1,'tap',0],[12.7,0,'tap',0],[13.15,2,'tap',0],[13.7,0,'tap',0],[13.95,1,'tap',0],[14.2,2,'tap',0],[14.45,3,'tap',0],[15.2,2,'hold',1],[16.35,0,'tap',0],[16.8,3,'tap',0],[17.25,1,'tap',0],[18,0,'tap',0],[18.45,2,'tap',0],[18.9,1,'hold',.9],[20,3,'tap',0],[20.55,0,'tap',0],[21,1,'tap',0],[21.45,2,'tap',0],[21.9,3,'tap',0]];return chart.map((x,i)=>({id:i,time:x[0],lane:x[1],type:x[2],duration:x[3],hit:false,missed:false,el:null}))}
function hud(){ $('gameplayScore').textContent=Math.round(score).toLocaleString();$('gameplayScoreFill').style.width=`${Math.min(100,score/1000)}%`;$('gameplayComboNumber').textContent=combo }
function judge(t){const e=$('gameplayJudgement');e.textContent=t;e.classList.remove('show');void e.offsetWidth;e.classList.add('show')}
function addNote(n,area){const e=document.createElement('div');e.className='gameplay-note';e.style.left=`${n.lane*25+12.5}%`;if(n.type==='hold'){e.classList.add('hold');e.style.height=`${Math.max(n.duration,.1)*160+36}px`};area.appendChild(e);n.el=e}
function loop(){if(ended)return;const area=$('gameplayLaneArea');if(!area)return;const time=gameplayAudio?gameplayAudio.currentTime:performance.now()/1000;const hitLine=area.clientHeight-110;gameplayNotes.forEach(n=>{if(!n.el&&time>=n.time-2)addNote(n,area);if(!n.el||n.hit||n.missed)return;const d=n.time-time;const progress=1-d/2;n.el.style.transform=`translate(-50%,${-60+(hitLine+60)*progress}px)`;if(d<-HIT){n.missed=true;miss++;combo=0;n.el.remove();n.el=null;judge('MISS');hud()}});if(gameplayNotes.every(n=>n.hit||n.missed)){finish()}else gameplayFrame=requestAnimationFrame(loop)}
function hit(lane){if(ended||!gameplayAudio)return;const t=gameplayAudio.currentTime;let target=null,closest=Infinity;gameplayNotes.forEach(n=>{if(n.hit||n.missed||n.lane!==lane)return;const d=Math.abs(n.time-t);if(d<=HIT&&d<closest){closest=d;target=n}});if(!target){combo=0;judge('MISS');hud();return}target.hit=true;combo++;let j='OKAY',mult=.5;if(closest<=.07){j='PERFECT';mult=1;perfect++}else if(closest<=.14){j='GREAT';mult=.8;great++}else okay++;score=Math.min(100000,score+(100000/gameplayNotes.length)*mult);if(target.el){target.el.classList.add('hit');setTimeout(()=>target.el?.remove(),120)}judge(j);hud()}
function finish(){if(ended)return;ended=true;cancelAnimationFrame(gameplayFrame);if(gameplayAudio){gameplayAudio.pause()}const rank=score>=95000?'S':score>=85000?'A':score>=70000?'B':score>=50000?'C':'D';$('gameplayResultScore').textContent=Math.round(score).toLocaleString();$('gameplayResultRank').textContent=rank;$('resultPerfect').textContent=perfect;$('resultGreat').textContent=great;$('resultOkay').textContent=okay;$('resultMiss').textContent=miss;$('gameplayResultTitle').textContent=rank==='S'||rank==='A'?'COMPLETE':'CLEAR';$('gameplayResult').classList.remove('hidden')}
function stop(){ended=true;cancelAnimationFrame(gameplayFrame);if(gameplayAudio){gameplayAudio.pause();gameplayAudio.currentTime=0;gameplayAudio.src='';gameplayAudio.load();gameplayAudio=null}}
function start(){document.body.classList.add('gameplay-active');$('gameplaySongName').textContent=NOW_PLAY_SONGS[selectedNowPlaySong]?.name||'VIRTUAL TO LIVE';$('gameplayDifficulty').textContent=selectedNowPlayDifficulty;gameplayNotes=createNotes();score=combo=perfect=great=okay=miss=0;ended=false;hud();const src=GAMEPLAY_SONGS[selectedNowPlaySong];if(src){gameplayAudio=new Audio(src);gameplayAudio.volume=.8;gameplayAudio.addEventListener('ended',finish,{once:true});gameplayAudio.play().catch(()=>{})}gameplayFrame=requestAnimationFrame(loop)}
[0,1,2,3].forEach(lane=>{const b=$(`laneButton${lane}`);if(b){b.addEventListener('pointerdown',e=>{e.preventDefault();b.classList.add('active');hit(lane)});['pointerup','pointerleave','pointercancel'].forEach(ev=>b.addEventListener(ev,()=>b.classList.remove('active')))}});
$('gameplayBackButton')?.addEventListener('click',()=>{stop();location.href='index(2).html?return=nowplay'});$('gameplayResultBack')?.addEventListener('click',()=>{stop();location.href='index(2).html?return=nowplay'});$('gameplaySkillButton')?.addEventListener('click',()=>{judge('SKILL');score=Math.min(100000,score+5000);hud();$('gameplaySkillButton').disabled=true});
start();
